### ISSUE TITLE
Sample server doesn't run

### ISSUE THREAD

**Issue by davidchappelle** [infusion/node-dhcp#16]
dchappelle@L164:~/macgyver2/node-dhcp/examples$ node server.js 
/home/dchappelle/macgyver2/node-dhcp/examples/server.js:65
s.listen();
  ^

TypeError: s.listen is not a function
    at Object.<anonymous> (/home/dchappelle/macgyver2/node-dhcp/examples/server.js:65:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by infusion** [comment]
How did you install the module? Have you installed the dependencies or just cloned the repo? Could you please debug what `s` is that no listen method is defined on it?
