### ISSUE TITLE
invalid option undefined

### ISSUE THREAD

**Issue by YovanggaAnandhika** [infusion/node-dhcp#73]
i am test the code.

i am tested run in windows 10 mode DHCP Server. and got error
```
Option 97 not known
Option 93 not known
Option 94 not known
{
  op: 1,
  htype: 1,
  hlen: 6,
  hops: 0,
  xid: 2764380901,
  secs: 16,
  flags: 32768,
  ciaddr: '0.0.0.0',
  yiaddr: '0.0.0.0',
  siaddr: '0.0.0.0',
  giaddr: '0.0.0.0',
  chaddr: '44-1E-A1-C5-1A-E5',
  sname: '',
  file: '',
  magicCookie: 1669485411,
  options: {
    '53': 1,
    '55': [
       1,   2,   3,   4,   5,   6,  11,  12,  13,
      15,  16,  17,  18,  22,  23,  28,  40,  41,
      42,  43,  50,  51,  54,  58,  59,  60,  66,
      67, 128, 129, 130, 131, 132, 133, 134, 135
    ],
    '57': 1260,
    '60': 'PXEClient:Arch:00000:UNDI:002001'
  }
}
F:\PEKERJAAN\DKA\DKAFramework\Sample\JS\node_modules\dhcp\lib\dhcp.js:148
      throw new Error('Invalid option ' + key);
      ^

Error: Invalid option undefined
    at Server.config (F:\PEKERJAAN\DKA\DKAFramework\Sample\JS\node_modules\dhcp\lib\dhcp.js:148:13)
    at Server._getOptions (F:\PEKERJAAN\DKA\DKAFramework\Sample\JS\node_modules\dhcp\lib\dhcp.js:216:30)
    at Server.sendOffer (F:\PEKERJAAN\DKA\DKAFramework\Sample\JS\node_modules\dhcp\lib\dhcp.js:388:21)
    at Server.handleDiscover (F:\PEKERJAAN\DKA\DKAFramework\Sample\JS\node_modules\dhcp\lib\dhcp.js:366:10)
    at Socket.<anonymous> (F:\PEKERJAAN\DKA\DKAFramework\Sample\JS\node_modules\dhcp\lib\dhcp.js:93:16)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at UDP.onMessage (node:dgram:931:8)
```

**Comment by infusion** [comment]
Do you have a computer booting using PXE or where are those PXE messages from?

**Comment by YovanggaAnandhika** [comment]
I run the program without setting anything on the local machine (project only). and a little setting in network properties.
pxe message appears in my windows terminal console log.
in the client side bios it doesn't detect any PXE boot.
but the console terminal detected an invalid error option.

is it necessary to add a support option code?

https://ibb.co/sPQf2km

**Comment by olamarvel** [comment]
please is there a solution to this also running into a similar issue

**Comment by infusion** [comment]
Fixed with next release
